theme: jekyll-theme-slate
title: Ester Bonmati
description: Senior Research Fellow - WEISS Fellowship \n Wellcome / EPSRC Centre for Interventional and Surgical Sciences (WEISS) / Department of Medical Physics and Biomedical Engineering / University College London (UCL)
