theme: jekyll-theme-slate
title: Ester Bonmati
description: |
  Senior Research Fellow (WEISS Fellowship) at the Wellcome / EPSRC Centre for Interventional and Surgical Sciences (WEISS) 
  and the UCL Medical Physics and Biomedical Engineering department at University College London (UCL).
